# Backend: METPO OWL file (src/ontology/metpo.owl)
# Purpose: List chemical interaction properties (subproperties of metpo:2000001)
# Used by: Schema documentation and property hierarchy analysis
# Returns: All object properties related to chemical interactions

select
?chem_interaction_prop ?label
where
{
  ?chem_interaction_prop <http://www.w3.org/2000/01/rdf-schema#subPropertyOf> <https://w3id.org/metpo/2000001> .
  optional {
    ?chem_interaction_prop <http://www.w3.org/2000/01/rdf-schema#label> ?label .
  }
}

