blank_issues_enabled: true
contact_links:
  - name: Contributing guide
    url: https://github.com/berkeleybop/metpo/blob/main/CONTRIBUTING.md
    about: How to propose terms, file issues, and open PRs for METPO.
