PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?sc ?p ?oc (COUNT(?s) AS ?count)
WHERE {
  ?s ?p ?o .
  OPTIONAL { ?s <https://w3id.org/biolink/vocab/category> ?sc . }
  OPTIONAL { ?o <https://w3id.org/biolink/vocab/category> ?oc . }
  FILTER(CONTAINS(STR(?p),"https://w3id.org/biolink/vocab/"))
}
GROUP BY ?sc ?p ?oc
order by ?sc ?p ?oc

# EXCLUDES
#http://purl.org/dc/terms/description
#https://www.example.org/UNKNOWN/meta
#https://www.example.org/UNKNOWN/primary_knowledge_source.1
#https://www.example.org/UNKNOWN/subsets
#rdf:object
#rdf:predicate
#rdf:subject
#rdf:type
#rdfs:label
