PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select
?n (count(?p) as ?count)
where {
    ?s rdf:type <http://example.com/n4l_metpo/organism> ;
    ?p ?o .
    graph <http://example.com/n4l_metpo/direct_ncbitaxid_same_as> {
        ?s owl:sameAs ?n .
    }
}
group by ?n
order by desc(count(?p))
limit 99
